# Spring
spring:
  application:
    name: msic
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd/MM/yyyy HH:mm:ss
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@hmsic_tp?TNS_ADMIN=src/main/resources/wallet
    username: ADMIN
    password: Nhiteahihi@123

idp:
  private-key: privateKey.rsa
  public-key: publicKey.rsa

s3:
  endpoint: http://localhost:9000
  bucket: msic-avatars
  region: us-east-1
  access-key: minioadmin
  secret-key: minioadmin
  public-url: http://localhost:9000/msic-avatars